// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ueukbmwxdfftcjytutis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVldWtibXd4ZGZmdGNqeXR1dGlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzgwOTMsImV4cCI6MjA1OTM1NDA5M30.zpgLHsfH5Nyj6dNVCw09RAQbNcjz3GSt9ssKQmemNuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);